POST http://127.0.0.1:5000/cadastro
content-type: application/json

{
    "login": "ana",
    "senha": "asdf"
}

###
POST http://127.0.0.1:5000/cadastro
content-type: application/json

{
    "login": "",
    "senha": "213123"
}
###
POST http://127.0.0.1:5000/login
content-type: application/json
# Obtain the access token

{
    "login": "ana",
    "senha": "asdf"
}

###
POST http://127.0.0.1:5000/produtos/echo
content-type: application/json
Authorization: Bearer PasteYourAccessTokenHere

{
	"nome": "Alpha Produto",
    "quantidade": 5,
    "valor": 34.56,
    "descricao": "Alpha produto descrição importante aqui."
}

###
POST http://127.0.0.1:5000/produtos/echo
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTU5NDI4ODcsIm5iZiI6MTU5NTk0Mjg4NywianRpIjoiYjkyZWU0YWQtMmUwZS00N2VmLThmM2UtNjA1YzYyMzg3NzNiIiwiZXhwIjoxNTk1OTQzNzg3LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.7DLzwQwYF4POI5SLmGeyq3kGpWvSsG6RhpkFwGDlDVA

{
	"nome": "Echo Produto",
    "quantidade": 33,
    "valor": 99.89,
    "descricao": "Echo produto descrição importante aqui."
}

###
GET http://127.0.0.1:5000/produtos
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTU5NDI4ODcsIm5iZiI6MTU5NTk0Mjg4NywianRpIjoiYjkyZWU0YWQtMmUwZS00N2VmLThmM2UtNjA1YzYyMzg3NzNiIiwiZXhwIjoxNTk1OTQzNzg3LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.7DLzwQwYF4POI5SLmGeyq3kGpWvSsG6RhpkFwGDlDVA


###
GET http://127.0.0.1:5000/produtos/echo
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTU4MTQ0NjIsIm5iZiI6MTU5NTgxNDQ2MiwianRpIjoiODc0YTE0MzUtMzFhZS00MWMxLThkNzktOWVlNWEyNGM4ZDc0IiwiZXhwIjoxNTk1ODE1MzYyLCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.6zRHsgQpNLZtpKsXBDRftS5lCVKBj_Ctjw6vwW3PA6U

###
PUT http://127.0.0.1:5000/produtos/echo
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTU4MTQ0NjIsIm5iZiI6MTU5NTgxNDQ2MiwianRpIjoiODc0YTE0MzUtMzFhZS00MWMxLThkNzktOWVlNWEyNGM4ZDc0IiwiZXhwIjoxNTk1ODE1MzYyLCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.6zRHsgQpNLZtpKsXBDRftS5lCVKBj_Ctjw6vwW3PA6U

{
    "nome": "Echo MASTER Produto",
    "quantidade": 50,
    "valor": 199.89,
    "descricao": "Echo MASTER produto descrição importante aqui."
}

###
DELETE http://127.0.0.1:5000/produtos/echo
content-type: application/json
Authorization: Bearer PasteYourAccessTokenHere


###
GET http://127.0.0.1:5000/usuarios/2
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTU4ODg4NTksIm5iZiI6MTU5NTg4ODg1OSwianRpIjoiYzdmNWEwZjEtNmIzOC00MDA0LWEyNjYtNjkzYTg2ZDUxYzBhIiwiZXhwIjoxNTk1ODg5NzU5LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.pVaSzGWvmShWL-lXWlLPM-LOeLUrjUhaMbak67v9x4o


###
PUT http://127.0.0.1:5000/usuarios/1
content-type: application/json
Authorization: Bearer PasteYourAccessTokenHere

{
    "login": "anaA",
    "senha": "1234"
}

###
DELETE http://127.0.0.1:5000/usuarios/2
content-type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTU4NjA1MzUsIm5iZiI6MTU5NTg2MDUzNSwianRpIjoiMTBiNmY3NDQtZDcxZC00YzNhLTk2NTUtNDBiZTYxMWFkNTVmIiwiZXhwIjoxNTk1ODYxNDM1LCJpZGVudGl0eSI6MSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.5UdL1ZnyuGtPZt1eDFm3WzjOIjpSCGTQtUZkieKM6tM


###
POST http://127.0.0.1:5000/logout
content-type: application/json
Authorization: Bearer PasteYourAccessTokenHere

